[package]
name = "society-bot"
version = "0.1.0"
authors = ["reslario <44400244+reslario@users.noreply.github.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.22"
json = "0.12.0"
serde_json = "1.0.42"
serde = "1.0.103"
select = "0.4.3"
regex = "1.3.1"
once_cell = "1.2.0"

